name: py-rocket-geospatial-qgis
channels:
  - conda-forge
  - nodefaults

dependencies:
  # Desktop tools
  - qgis 
  - pyopencl  # Maybe needed for qgis? https://github.com/conda-forge/qgis-feedstock/issues/263
  # Resolves warning "No ICDs were found": https://github.com/CryoInTheCloud/hub-image/issues/50
  - ocl-icd-system
