name: Docker Image Build and Push Geospatial

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'action.yml'
      - '.github/workflows/build-and-push-geospatial.yml'
      - 'images/py-rocket-geospatial-qgis/**'
      - 'images/py-rocket-geospatial/**'
      - 'images/py-geospatial/**'

env:
  WATCHED_DIRECTORIES: |
    images/py-geospatial
    images/py-rocket-geospatial
    images/py-rocket-geospatial-qgis

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.find-changes.outputs.matrix_dirs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Find changed directories
        id: find-changes
        run: |
          # Prepare the watched directories list as a single line with | separator
          watched_dirs=$(echo "${WATCHED_DIRECTORIES}" | tr '\n' '|')
          all_changed_dirs=$(git diff --name-only HEAD^ HEAD | grep -E "^(${watched_dirs})" | sort -u)
          echo "Debugging: all_changed_dirs is $all_changed_dirs"
          # Now apply sed to reduce each path to the top-level watched directory
          dirs=$(echo "$all_changed_dirs" | while read -r path; do
            # Match the path to one of the watched directories, preserving only the matched part
            for watched in ${WATCHED_DIRECTORIES}; do
              if [[ "$path" == "$watched" || "$path" == "$watched/"* ]]; then
              echo "$watched"
              fi
            done
          done | sort -u | uniq)

          echo "Filtered directories: $dirs"
          
          echo "Debugging: all_changed_dirs is $dirs"
          if [ -z "$dirs" ]; then
            echo "No changed directories"
            echo "::set-output name=matrix_dirs::[]"  # Set an empty array to handle no changes
            exit 0
          fi
          
          # Convert to JSON array for matrix strategy
          matrix_dirs=$(echo "$dirs" | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "::set-output name=matrix_dirs::$matrix_dirs"
          echo "Debugging: matrix_dirs output is $matrix_dirs"

  build-py-geospatial:
    runs-on: ubuntu-latest
    needs: find-changes
    if: ${{ needs.find-changes.outputs.matrix_dirs != '[]' && contains(fromJson(needs.find-changes.outputs.matrix_dirs), 'images/py-geospatial') }}
    steps:
      - uses: actions/checkout@v3
      - name: Build py-geospatial
        uses: nmfs-opensci/container-images@main
        with:
          image_dir: images/py-geospatial
          image_name: container-images/py-geospatial
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-py-rocket-geospatial:
    runs-on: ubuntu-latest
    needs: build-py-geospatial
    if: ${{ needs.find-changes.outputs.matrix_dirs != '[]' && contains(fromJson(needs.find-changes.outputs.matrix_dirs), 'images/py-rocket-geospatial') }}
    steps:
      - uses: actions/checkout@v3
      - name: Build py-rocket-geospatial
        uses: nmfs-opensci/container-images@main
        with:
          image_dir: images/py-rocket-geospatial
          image_name: container-images/py-rocket-geospatial
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-py-rocket-geospatial-qgis:
    runs-on: ubuntu-latest
    needs: build-py-rocket-geospatial
    if: ${{ needs.find-changes.outputs.matrix_dirs != '[]' && contains(fromJson(needs.find-changes.outputs.matrix_dirs), 'images/py-rocket-geospatial-qgis') }}
    steps:
      - uses: actions/checkout@v3
      - name: Build py-rocket-geospatial-qgis
        uses: nmfs-opensci/container-images@main
        with:
          image_dir: images/py-rocket-geospatial-qgis
          image_name: container-images/py-rocket-geospatial-qgis
          github_token: ${{ secrets.GITHUB_TOKEN }}
