name: Docker Image CI AOML-omics
on:
  workflow_dispatch: null
  push:
    branches: main
    paths: 
      - '!images/aomlomics-jh/README.md'
      - 'images/aomlomics-jh/**'
      - '.github/workflows/docker-image-aomlomics-jh.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'nmfs-opensci/container-images'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker build images/aomlomics-jh -f images/aomlomics-jh/Dockerfile  --tag ghcr.io/nmfs-opensci/container-images/aomlomics-jh:latest
      - name: Publish
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker push ghcr.io/nmfs-opensci/container-images/aomlomics-jh:latest

